/**
 * Generates data/leadgen-history.json: SYNTHETIC past-campaign outcomes for the
 * learning loop demo. A hidden "true" model (different from the expert priors) labels
 * randomly drawn prospects, so a learning cycle has something real to discover:
 * (label = a positive reply or booked meeting). Absentee owners and long vacancies convert better than the priors assume; recent
 * buyers and eviction filings convert worse. Deterministic (seeded).
 *
 *   node scripts/generate-history.js
 */
import { writeFileSync } from "node:fs";
import { seededRandom } from "../src/playbooks/leadgen/learning.js";

const TRUE = { bias: -4.2, w: { absentee: 1.7, listedForRent: 0.4, domOver30: 1.5, priceCut: 1.0, selfManaged: 0.6, doors2to10: 0.9, recentPurchase: -0.6, evictionFiling: -0.2, codeViolation: 0.0 } };
const rng = seededRandom(20261002);
const coin = (p) => (rng() < p ? 1 : 0);

const samples = [];
for (let i = 0; i < 500; i++) {
  const listedForRent = coin(0.55);
  const x = {
    absentee: coin(0.35),
    listedForRent,
    domOver30: listedForRent ? coin(0.45) : 0,
    priceCut: listedForRent ? coin(0.3) : 0,
    selfManaged: coin(0.7),
    doors2to10: coin(0.4),
    recentPurchase: coin(0.15),
    evictionFiling: coin(0.08),
    codeViolation: coin(0.1),
  };
  const z = TRUE.bias + Object.entries(x).reduce((s, [k, v]) => s + TRUE.w[k] * v, 0);
  const y = coin(1 / (1 + Math.exp(-z)));
  samples.push({ x, y });
}

const bandit = {
  A: { V1: { a: 7, b: 63 }, V2: { a: 12, b: 58 }, V3: { a: 16, b: 44 } },
  B: { V1: { a: 9, b: 141 }, V2: { a: 14, b: 136 }, V3: { a: 13, b: 87 } },
};

writeFileSync(
  new URL("../data/leadgen-history.json", import.meta.url),
  JSON.stringify({ note: "SYNTHETIC campaign history for the learning-loop demo — generated by scripts/generate-history.js, not real data.", positives: samples.filter((s) => s.y).length, bandit, samples }) + "\n"
);
console.log(`wrote ${samples.length} samples (${samples.filter((s) => s.y).length} positive)`);
