// Sehrish Builders — product & category data
const CATEGORIES = [
  { id: "cement-binders", name: "Cement & Binders", icon: "package" },
  { id: "bricks-blocks", name: "Bricks & Blocks", icon: "blocks" },
  { id: "steel-hardware", name: "Steel & Hardware", icon: "hammer" },
  { id: "plumbing", name: "Plumbing", icon: "droplets" },
  { id: "electrical", name: "Electrical", icon: "zap" },
  { id: "sand-aggregate", name: "Sand & Aggregate", icon: "mountain" },
  { id: "finishing-materials", name: "Finishing Materials", icon: "paint-bucket" },
  { id: "tools-hardware", name: "Tools & Hardware", icon: "wrench" },
];

const PRODUCTS = [
  {
    id: 1,
    name: "Portland Cement",
    category: "Cement & Binders",
    price: 1450,
    unit: "per 50kg bag",
    availability: "In Stock",
    description: "Standard-grade Portland cement suitable for concrete, plastering and general construction work.",
    image: "https://images.unsplash.com/photo-1457414104202-9d4b4908f285?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 2,
    name: "White Cement",
    category: "Cement & Binders",
    price: 1250,
    unit: "per 40kg bag",
    availability: "Limited Stock",
    description: "Fine white cement used for decorative finishes, tile grouting and surface repairs.",
    image: "https://images.unsplash.com/photo-1730627283177-f43b83c3850c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 3,
    name: "Red Bricks",
    category: "Bricks & Blocks",
    price: 25,
    unit: "per piece",
    availability: "In Stock",
    description: "Standard clay bricks for walls, boundary construction and general masonry work.",
    image: "https://images.unsplash.com/photo-1495578942200-c5f5d2137def?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 4,
    name: "Concrete Blocks",
    category: "Bricks & Blocks",
    price: 120,
    unit: "per piece",
    availability: "In Stock",
    description: "Solid concrete blocks used for load-bearing and partition walls.",
    image: "https://images.unsplash.com/photo-1680700688903-99102eaa0dcf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 5,
    name: "Steel Rebar 10mm",
    category: "Steel & Hardware",
    price: 280,
    unit: "per kg",
    availability: "In Stock",
    description: "10mm deformed steel bar used for reinforced concrete structures.",
    image: "https://images.unsplash.com/photo-1761479867761-7a8b11f54449?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 6,
    name: "Steel Rebar 12mm",
    category: "Steel & Hardware",
    price: 285,
    unit: "per kg",
    availability: "In Stock",
    description: "12mm deformed steel bar for columns, beams and slab reinforcement.",
    image: "https://images.unsplash.com/photo-1623428454598-1bfe414bac03?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 7,
    name: "Binding Wire",
    category: "Steel & Hardware",
    price: 250,
    unit: "per kg",
    availability: "In Stock",
    description: "Soft-annealed binding wire for tying steel rebar during construction.",
    image: "https://images.unsplash.com/photo-1603577892348-ea14a00f2950?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 8,
    name: "Construction Sand",
    category: "Sand & Aggregate",
    price: 2500,
    unit: "per 100 cft",
    availability: "In Stock",
    description: "Washed construction sand suitable for concrete mixing and plastering.",
    image: "https://images.unsplash.com/photo-1785791516517-aae4ca2fcfcb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 9,
    name: "Crush Aggregate",
    category: "Sand & Aggregate",
    price: 3500,
    unit: "per 100 cft",
    availability: "In Stock",
    description: "Crushed stone aggregate for concrete mixing and base preparation.",
    image: "https://images.unsplash.com/photo-1620914695139-9507be60a425?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 10,
    name: "PVC Water Pipe",
    category: "Plumbing",
    price: 850,
    unit: "per 10ft pipe",
    availability: "In Stock",
    description: "PVC pipe for cold water supply and general plumbing lines.",
    image: "https://images.unsplash.com/photo-1586057285471-2f78bffaf074?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 11,
    name: "PVC Elbow",
    category: "Plumbing",
    price: 250,
    unit: "per piece",
    availability: "In Stock",
    description: "PVC elbow fitting for changing pipe direction in plumbing lines.",
    image: "https://images.unsplash.com/photo-1682540963112-facad29c3fa2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 12,
    name: "Electrical Conduit Pipe",
    category: "Electrical",
    price: 450,
    unit: "per 10ft pipe",
    availability: "In Stock",
    description: "PVC conduit pipe for concealed electrical wiring.",
    image: "https://images.unsplash.com/photo-1543674892-7d64d45df18b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 13,
    name: "Tile Adhesive",
    category: "Finishing Materials",
    price: 950,
    unit: "per 20kg bag",
    availability: "In Stock",
    description: "Cement-based adhesive for fixing floor and wall tiles.",
    image: "https://images.unsplash.com/photo-1599209250635-26c180f28419?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 14,
    name: "Wall Putty",
    category: "Finishing Materials",
    price: 1200,
    unit: "per 20kg bag",
    availability: "In Stock",
    description: "White cement-based putty for smoothing interior and exterior walls before painting.",
    image: "https://images.unsplash.com/photo-1615800098779-1be32e60cca3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 15,
    name: "Waterproofing Compound",
    category: "Finishing Materials",
    price: 1800,
    unit: "per 20kg drum",
    availability: "Limited Stock",
    description: "Liquid waterproofing compound for roofs, bathrooms and water tanks.",
    image: "https://images.unsplash.com/photo-1674485169641-bcb2bf6f1df9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 16,
    name: "Construction Nails",
    category: "Tools & Hardware",
    price: 350,
    unit: "per kg",
    availability: "In Stock",
    description: "Steel nails for general carpentry and construction use.",
    image: "https://images.unsplash.com/photo-1617123623686-2b7b339785da?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 17,
    name: "Gypsum Board",
    category: "Finishing Materials",
    price: 1500,
    unit: "per sheet",
    availability: "In Stock",
    description: "Gypsum board sheet for false ceilings and partition walls.",
    image: "https://images.unsplash.com/photo-1504149806848-6b24bfe86a7f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 18,
    name: "PVC Floor Drain",
    category: "Plumbing",
    price: 550,
    unit: "per piece",
    availability: "Limited Stock",
    description: "PVC floor drain fitting for bathrooms and open areas.",
    image: "https://images.unsplash.com/photo-1586057285471-2f78bffaf074?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 19,
    name: "Mason Trowel",
    category: "Tools & Hardware",
    price: 650,
    unit: "per piece",
    availability: "In Stock",
    description: "Steel mason trowel for plastering and brickwork.",
    image: "https://images.unsplash.com/photo-1588399944136-efbd34b99d6b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
  {
    id: 20,
    name: "Measuring Tape",
    category: "Tools & Hardware",
    price: 450,
    unit: "per piece",
    availability: "In Stock",
    description: "Retractable steel measuring tape for site measurements.",
    image: "https://images.unsplash.com/photo-1703756291638-b1774ae3c186?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
  },
];
