import { Router } from 'express';
import { adjustmentsRouter } from './adjustments.js';
import { auditRouter } from './audit.js';
import { brandsRouter } from './brands.js';
import { categoriesRouter } from './categories.js';
import { customersRouter } from './customers.js';
import { dashboardRouter } from './dashboard.js';
import { inventoryRouter } from './inventory.js';
import { locationsRouter } from './locations.js';
import { notificationsRouter } from './notifications.js';
import { productsRouter } from './products.js';
import { purchasesRouter } from './purchases.js';
import { reportsRouter } from './reports.js';
import { returnsRouter } from './returns.js';
import { salesRouter } from './sales.js';
import { searchRouter } from './search.js';
import { settingsRouter } from './settings.js';
import { stockCountsRouter } from './stock-counts.js';
import { suppliersRouter } from './suppliers.js';
import { transfersRouter } from './transfers.js';
import { usersRouter } from './users.js';

export const apiRouter = Router();

apiRouter.use('/audit-logs', auditRouter);
apiRouter.use('/brands', brandsRouter);
apiRouter.use('/categories', categoriesRouter);
apiRouter.use('/customers', customersRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/inventory', inventoryRouter);
apiRouter.use('/locations', locationsRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/products', productsRouter);
apiRouter.use('/purchases', purchasesRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/returns', returnsRouter);
apiRouter.use('/sales', salesRouter);
apiRouter.use('/search', searchRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/stock-adjustments', adjustmentsRouter);
apiRouter.use('/stock-counts', stockCountsRouter);
apiRouter.use('/stock-transfers', transfersRouter);
apiRouter.use('/suppliers', suppliersRouter);
apiRouter.use('/users', usersRouter);
