import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, Bell, CheckCheck, PackageX } from 'lucide-react';
import { api, type ListResponse } from '@/lib/api';
import type { Notification } from '@/types';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { relativeTime, cn } from '@/lib/utils';

const ICONS = {
  OUT_OF_STOCK: PackageX,
  LOW_STOCK: AlertTriangle,
} as const;

export function NotificationBell() {
  const queryClient = useQueryClient();

  const { data } = useQuery({
    queryKey: ['notifications', 'bell'],
    queryFn: () => api.get<ListResponse<Notification>>('/notifications', { pageSize: 8 }),
    // Alerts are generated by stock movements, so poll gently rather than
    // holding a socket open.
    refetchInterval: 60_000,
  });

  const markAll = useMutation({
    mutationFn: () => api.post('/notifications/read-all'),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['notifications'] }),
  });

  const unread = data?.meta.unread ?? 0;
  const items = data?.data ?? [];

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon" className="relative" aria-label={`Notifications (${unread} unread)`}>
          <Bell className="h-5 w-5" />
          {unread > 0 ? (
            <span className="absolute right-1.5 top-1.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-destructive px-1 text-[10px] font-bold text-destructive-foreground">
              {unread > 99 ? '99+' : unread}
            </span>
          ) : null}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-[min(22rem,calc(100vw-1.5rem))] p-0">
        <div className="flex items-center justify-between px-3 py-2.5">
          <p className="text-sm font-semibold">Notifications</p>
          {unread > 0 ? (
            <button
              type="button"
              onClick={() => markAll.mutate()}
              className="flex items-center gap-1 text-xs text-muted-foreground transition-colors hover:text-foreground"
            >
              <CheckCheck className="h-3.5 w-3.5" />
              Mark all read
            </button>
          ) : null}
        </div>
        <DropdownMenuSeparator className="mx-0" />
        <div className="max-h-80 overflow-y-auto scrollbar-thin">
          {items.length === 0 ? (
            <p className="px-3 py-8 text-center text-sm text-muted-foreground">You are all caught up.</p>
          ) : (
            items.map((item) => {
              const Icon = ICONS[item.type as keyof typeof ICONS] ?? Bell;
              return (
                <div
                  key={item.id}
                  className={cn('flex gap-2.5 px-3 py-2.5', !item.isRead && 'bg-accent/50')}
                >
                  <Icon
                    className={cn(
                      'mt-0.5 h-4 w-4 shrink-0',
                      item.level === 'CRITICAL' ? 'text-destructive' : 'text-amber-600',
                    )}
                  />
                  <div className="min-w-0">
                    <p className="text-sm font-medium leading-snug">{item.title}</p>
                    <p className="text-xs leading-snug text-muted-foreground">{item.message}</p>
                    <p className="mt-0.5 text-[11px] text-muted-foreground">{relativeTime(item.createdAt)}</p>
                  </div>
                </div>
              );
            })
          )}
        </div>
        <DropdownMenuSeparator className="mx-0" />
        <Link
          to="/notifications"
          className="block px-3 py-2.5 text-center text-sm font-medium text-primary hover:underline"
        >
          View all notifications
        </Link>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
