"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-21 19:57:05.252612

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('first_order_at', sa.DateTime(), nullable=True),
    sa.Column('last_order_at', sa.DateTime(), nullable=True),
    sa.Column('order_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('return_order_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('return_amount', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('net_revenue', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('units', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('distinct_products', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index('ix_customers_country', 'customers', ['country'], unique=False)
    op.create_index('ix_customers_last_order_at', 'customers', ['last_order_at'], unique=False)
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('rows_read', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_accepted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_excluded', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('rows_flagged', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sheets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_runs_file_sha256'), 'import_runs', ['file_sha256'], unique=False)
    op.create_index('ux_import_runs_sha256_succeeded', 'import_runs', ['file_sha256'], unique=True, postgresql_where=sa.text("status = 'succeeded'"))
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'trained'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_cutoff', sa.Date(), nullable=True),
    sa.Column('scoring_cutoff', sa.Date(), nullable=True),
    sa.Column('train_start', sa.Date(), nullable=True),
    sa.Column('train_end', sa.Date(), nullable=True),
    sa.Column('validation_start', sa.Date(), nullable=True),
    sa.Column('validation_end', sa.Date(), nullable=True),
    sa.Column('test_start', sa.Date(), nullable=True),
    sa.Column('test_end', sa.Date(), nullable=True),
    sa.Column('n_train', sa.Integer(), nullable=True),
    sa.Column('n_validation', sa.Integer(), nullable=True),
    sa.Column('n_test', sa.Integer(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('data_version', sa.String(length=64), nullable=True),
    sa.Column('code_version', sa.String(length=64), nullable=True),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version')
    )
    op.create_index('ix_model_runs_type_active', 'model_runs', ['model_type', 'is_active'], unique=False)
    op.create_table('products',
    sa.Column('stock_code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_non_product', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('first_sold_at', sa.DateTime(), nullable=True),
    sa.Column('last_sold_at', sa.DateTime(), nullable=True),
    sa.Column('units_sold', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('order_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('stock_code')
    )
    op.create_table('customer_segments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('cutoff_date', sa.Date(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('segment_name', sa.String(length=64), nullable=False),
    sa.Column('recency_days', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('monetary', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'customer_id', name='ux_customer_segments_run_customer')
    )
    op.create_index('ix_customer_segments_customer', 'customer_segments', ['customer_id'], unique=False)
    op.create_table('customer_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('cutoff_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('lookback_days', sa.Integer(), server_default=sa.text('365'), nullable=False),
    sa.Column('tenure_days', sa.Integer(), nullable=False),
    sa.Column('recency_days', sa.Integer(), nullable=False),
    sa.Column('orders_lifetime', sa.Integer(), nullable=False),
    sa.Column('spend_lifetime', sa.Float(), nullable=False),
    sa.Column('avg_order_value', sa.Float(), nullable=False),
    sa.Column('orders_lookback', sa.Integer(), nullable=False),
    sa.Column('spend_lookback', sa.Float(), nullable=False),
    sa.Column('orders_90', sa.Integer(), nullable=False),
    sa.Column('spend_90', sa.Float(), nullable=False),
    sa.Column('orders_60', sa.Integer(), nullable=False),
    sa.Column('spend_60', sa.Float(), nullable=False),
    sa.Column('orders_30', sa.Integer(), nullable=False),
    sa.Column('spend_30', sa.Float(), nullable=False),
    sa.Column('spend_prior_90', sa.Float(), nullable=False),
    sa.Column('spend_trend', sa.Float(), nullable=False),
    sa.Column('mean_interpurchase_days', sa.Float(), nullable=True),
    sa.Column('last_interpurchase_days', sa.Float(), nullable=True),
    sa.Column('distinct_products', sa.Integer(), nullable=False),
    sa.Column('return_orders_lifetime', sa.Integer(), nullable=False),
    sa.Column('return_amount_lifetime', sa.Float(), nullable=False),
    sa.Column('is_uk', sa.Boolean(), nullable=False),
    sa.Column('outcome_window_complete', sa.Boolean(), nullable=False),
    sa.Column('label_purchased', sa.Boolean(), nullable=True),
    sa.Column('label_spend', sa.Float(), nullable=True),
    sa.Column('dataset_split', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'cutoff_date', name='ux_customer_snapshots_customer_cutoff')
    )
    op.create_index('ix_customer_snapshots_cutoff', 'customer_snapshots', ['cutoff_date'], unique=False)
    op.create_index('ix_customer_snapshots_split', 'customer_snapshots', ['dataset_split'], unique=False)
    op.create_table('orders',
    sa.Column('invoice', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('order_at', sa.DateTime(), nullable=False),
    sa.Column('is_cancellation', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('line_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('product_line_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('units', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('return_amount', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('is_eligible_positive', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('invoice')
    )
    op.create_index('ix_orders_customer_order_at', 'orders', ['customer_id', 'order_at'], unique=False)
    op.create_index('ix_orders_eligible_positive', 'orders', ['is_eligible_positive'], unique=False)
    op.create_index('ix_orders_order_at', 'orders', ['order_at'], unique=False)
    op.create_table('raw_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=64), nullable=False),
    sa.Column('sheet_row', sa.Integer(), nullable=False),
    sa.Column('invoice_raw', sa.Text(), nullable=True),
    sa.Column('stock_code_raw', sa.Text(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('quantity_raw', sa.Text(), nullable=True),
    sa.Column('invoice_date_raw', sa.Text(), nullable=True),
    sa.Column('unit_price_raw', sa.Text(), nullable=True),
    sa.Column('customer_id_raw', sa.Text(), nullable=True),
    sa.Column('country_raw', sa.Text(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('exclusion_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_transactions_import_run_id'), 'raw_transactions', ['import_run_id'], unique=False)
    op.create_index('ix_raw_transactions_row_hash', 'raw_transactions', ['row_hash'], unique=False)
    op.create_index('ix_raw_transactions_run_status', 'raw_transactions', ['import_run_id', 'validation_status'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('prediction_type', sa.String(length=32), nullable=False),
    sa.Column('cutoff_date', sa.Date(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('predicted_spend', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['customer_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'customer_id', name='ux_predictions_run_customer')
    )
    op.create_index('ix_predictions_customer', 'predictions', ['customer_id'], unique=False)
    op.create_index('ix_predictions_run_rank', 'predictions', ['model_run_id', 'rank'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('raw_transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('invoice', sa.String(length=32), nullable=False),
    sa.Column('stock_code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('line_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_cancellation', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_non_product', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_eligible_sale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_eligible_return', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_transaction_id'], ['raw_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_transaction_id')
    )
    op.create_index('ix_transactions_customer_date', 'transactions', ['customer_id', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_transactions_import_run_id'), 'transactions', ['import_run_id'], unique=False)
    op.create_index('ix_transactions_invoice', 'transactions', ['invoice'], unique=False)
    op.create_index('ix_transactions_invoice_date', 'transactions', ['invoice_date'], unique=False)
    op.create_index('ix_transactions_stock_code', 'transactions', ['stock_code'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice', sa.String(length=32), nullable=False),
    sa.Column('stock_code', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('line_amount', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_eligible_sale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_eligible_return', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['invoice'], ['orders.invoice'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_code'], ['products.stock_code'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('ix_order_items_invoice', 'order_items', ['invoice'], unique=False)
    op.create_index('ix_order_items_stock_code', 'order_items', ['stock_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_stock_code', table_name='order_items')
    op.drop_index('ix_order_items_invoice', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_transactions_stock_code', table_name='transactions')
    op.drop_index('ix_transactions_invoice_date', table_name='transactions')
    op.drop_index('ix_transactions_invoice', table_name='transactions')
    op.drop_index(op.f('ix_transactions_import_run_id'), table_name='transactions')
    op.drop_index('ix_transactions_customer_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_predictions_run_rank', table_name='predictions')
    op.drop_index('ix_predictions_customer', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_raw_transactions_run_status', table_name='raw_transactions')
    op.drop_index('ix_raw_transactions_row_hash', table_name='raw_transactions')
    op.drop_index(op.f('ix_raw_transactions_import_run_id'), table_name='raw_transactions')
    op.drop_table('raw_transactions')
    op.drop_index('ix_orders_order_at', table_name='orders')
    op.drop_index('ix_orders_eligible_positive', table_name='orders')
    op.drop_index('ix_orders_customer_order_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_customer_snapshots_split', table_name='customer_snapshots')
    op.drop_index('ix_customer_snapshots_cutoff', table_name='customer_snapshots')
    op.drop_table('customer_snapshots')
    op.drop_index('ix_customer_segments_customer', table_name='customer_segments')
    op.drop_table('customer_segments')
    op.drop_table('products')
    op.drop_index('ix_model_runs_type_active', table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index('ux_import_runs_sha256_succeeded', table_name='import_runs', postgresql_where=sa.text("status = 'succeeded'"))
    op.drop_index(op.f('ix_import_runs_file_sha256'), table_name='import_runs')
    op.drop_table('import_runs')
    op.drop_index('ix_customers_last_order_at', table_name='customers')
    op.drop_index('ix_customers_country', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
