/**
 * Maintenance — vetted message templates.
 *
 * Safety instructions are NEVER generated by a model: they come from the emergency
 * SOP, reviewed once, filled with retrieved facts (e.g. where this unit's shutoff
 * valve is). Templates are also free, instant, and identical for every resident.
 */

import { usd } from "../../core/format.js";

const COMPANY = "Northwind Residential";

const SAFETY_STEPS = {
  water: (shutoff) =>
    `If you can do so safely: 1) close the water valve ${shutoff ?? "under your kitchen sink"}; 2) stay away from wet outlets and light fixtures — switch off that room's breaker only if you can reach the panel without touching water; 3) move valuables and put down towels or a bucket; 4) take photos.`,
  gas: () => "Please leave your home now. Don't use light switches, appliances or flames. From outside, call 911 and your gas utility's emergency line.",
  fire: () => "If there is fire or smoke, leave now and call 911. Don't go back inside until the fire department says it's safe.",
  electrical: () => "Stay away from the outlet or fixture. If it's safe, switch off that circuit at your breaker panel. If you see smoke or flames, leave and call 911.",
  sewage: () => "Please stop using sinks, showers, toilets and the dishwasher until the plumber arrives, and keep children and pets away from the affected area.",
  security: () => "If you are in danger or someone is inside, leave and call 911 now.",
  injury: () => "If anyone is hurt, call 911 now.",
  cold: () =>
    "Until the heat is back, use only safe heat sources — never a stove, oven, grill or generator indoors (carbon monoxide). Dress in layers and keep interior doors closed. If anyone is very young, elderly or unwell, or it gets dangerously cold, call 911 or go to a warming center.",
  heat: () =>
    "Until cooling is back, drink water, close the blinds, use fans and stay in the coolest room. If anyone feels dizzy, confused or faint, call 911.",
  structural: (shutoff) =>
    `Please keep everyone out of that room — more of the ceiling may come down. If anyone is hurt, call 911. If water is coming through, close the water valve ${shutoff ?? "under your kitchen sink"} if you can reach it safely.`,
};

/** Which vetted safety steps apply: the rule's own, else the category's. No match → no steps (never the wrong ones). */
const CATEGORY_SAFETY = { water_leak: "water", gas: "gas", fire: "fire", electrical: "electrical", sewage: "sewage", security: "security", injury: "injury", structural: "structural" };
export function safetyFor({ safety = null, category = null, rulesFired = [] }) {
  if (safety) return safety;
  if (category === "hvac") return rulesFired.some((r) => r.startsWith("no_cooling")) ? "heat" : rulesFired.some((r) => r.startsWith("no_heat")) ? "cold" : null;
  return CATEGORY_SAFETY[category] ?? null;
}

export const templates = {
  /** Same vetted steps as the SMS, for the voice fallback when a text can't be delivered. */
  emergencyVoice({ caseId, safety, shutoff }) {
    const steps = SAFETY_STEPS[safety]?.(shutoff) ?? "";
    return `This is Northwind maintenance about your emergency, case ${caseId.replace(/-/g, " ").split("").join(" ")}. Help is being arranged now. ${steps} We will call or text again with an update.`.replace(/\s+/g, " ").trim();
  },

  emergencyReply({ first, receivedAt, caseId, safety, shutoff, dispatching }) {
    const steps = SAFETY_STEPS[safety]?.(shutoff) ?? "";
    const help = dispatching ? "An emergency technician is being dispatched now and our on-call manager is being paged." : "Our on-call manager is being paged now.";
    return `Hi ${first}, this is ${COMPANY}'s 24/7 maintenance line. We received your message at ${receivedAt} and are treating it as an emergency (case ${caseId}). ${help} ${steps} We'll text you as soon as help is confirmed.`.replace(/\s+/g, " ").trim();
  },

  urgentAck({ first, caseId, when }) {
    return `Hi ${first}, thanks for letting us know — case ${caseId} is open and marked urgent. A technician will contact you ${when}. If anything gets worse (water spreading, sparks, a gas smell), reply here right away and we'll treat it as an emergency.`;
  },

  routineAck({ first, caseId }) {
    return `Hi ${first}, thanks — your request is logged as case ${caseId}. Our maintenance team will schedule it during business hours and text you a time window. Reply here if it gets worse.`;
  },

  sensitiveAck({ first, caseId, manager, by }) {
    return `Hi ${first}, thank you for telling us, and I'm sorry you're still dealing with this. I've escalated case ${caseId} to ${manager}, our property manager, who will contact you personally ${by}.`;
  },

  generalAck({ first, by }) {
    return `Hi ${first}, thanks for your message. I've passed it to our team and someone will reply ${by}. For anything urgent with your home (leaks, no heat, safety), reply here and say what's happening.`;
  },

  unknownSenderEmergency({ caseId }) {
    return `This is ${COMPANY}'s 24/7 maintenance line (case ${caseId}). We're paging our on-call manager now. If anyone is in danger, call 911. Please reply with your name and full address, including unit number, so we can send help to the right place.`;
  },

  unknownSenderAsk() {
    return `Thanks for contacting ${COMPANY} maintenance. So we can help, please reply with your name and the property address (including unit number).`;
  },

  vendorAssigned({ vendor, eta }) {
    return eta
      ? `Update: ${vendor} has accepted your emergency and is on the way — expected around ${eta}. We'll let you know when they arrive.`
      : `Update: ${vendor} has accepted your emergency and is on the way. We'll send their arrival time as soon as we have it.`;
  },

  nextVendor() {
    return "Update: the first plumber we called couldn't take the job, so we've contacted the next 24/7 plumber on our list. We'll update you within 10 minutes.";
  },

  humanOnIt({ staff }) {
    return `${staff} from our team now has your case and will call you shortly.`;
  },

  vendorOnSite({ vendor }) {
    return `${vendor} has arrived and is starting work.`;
  },

  checkin({ caseId }) {
    return `Checking in on case ${caseId}: is water still coming in? Reply 1 if it has stopped, 2 if it's still coming in.`;
  },

  stillLeaking() {
    return "Thanks for telling us. I've flagged this to our on-call manager and the technician as top priority. Keep clear of any wet outlets or fixtures.";
  },

  mitigated({ vendor, cause, nextStep }) {
    return `Good news — ${vendor} found the source${cause ? ` (${cause})` : ""} and the water is stopped.${nextStep ? ` Next: ${nextStep}. We'll confirm a time with you.` : ""}`;
  },

  repairScheduled({ when, work }) {
    return `Your repair is scheduled: ${work} — ${when}. Reply here if that time doesn't work.`;
  },

  resolved({ caseId }) {
    return `Case ${caseId} is resolved. Thank you for your patience. If anything comes back, just reply to this message.`;
  },

  // ── Neighbor (unit above) ──
  neighborCheck({ first }) {
    return `Hi ${first}, this is ${COMPANY} maintenance. We're responding to a possible water leak in the unit below yours. When you can, please check under your sinks and around your toilet, tub and water heater, and reply here with what you see. If you find water, please close the valve under your kitchen sink. Thank you!`;
  },
  neighborLeakFound() {
    return "Thank you — that's very helpful. If you can, please close the valve under your kitchen sink now. Our plumber is on the way and will check your unit first.";
  },
  neighborThanks() {
    return "Thanks for checking — that helps a lot. No action needed on your side.";
  },

  // ── Vendors ──
  dispatchSay({ address, unit, issue }) {
    return `This is ${COMPANY} emergency dispatch. ${issue} at ${address}, unit ${unit}. Press 1 to accept. Press 2 to decline.`;
  },
  dispatchSms({ caseId, address, unit, issue }) {
    return `EMERGENCY DISPATCH ${caseId}: ${issue} — ${address}, unit ${unit}. Reply 1 to accept (with your ETA) or 2 to decline. Our on-call manager will send access details.`;
  },
  vendorAskEta({ caseId }) {
    return `Thanks for accepting ${caseId}. Reply with your ETA in minutes so we can update the resident.`;
  },
  vendorNeighborUpdate({ caseId, aboveUnit, finding }) {
    return `Update on ${caseId}: the resident in ${aboveUnit} (unit above) reports ${finding}. Please check ${aboveUnit} first.`;
  },
  vendorCheckArrival({ caseId }) {
    return `Checking in on ${caseId}: are you on site? Reply with an updated ETA if you're delayed.`;
  },

  // ── Staff ──
  accessRequest({ vendor, caseId, eta }) {
    return `${vendor} accepted ${caseId}${eta ? ` (ETA ${eta})` : ""}. Please send them the lockbox/access details — the agent never sends access codes.`;
  },
  staffAlert({ caseId, text }) {
    return `[${caseId}] ${text}`;
  },

  // ── Owner ──
  ownerEmergency({ first, property, unit, issue, receivedAt, limit }) {
    return `Hi ${first}, ${COMPANY} here. Heads-up: an emergency (${issue}) was reported at ${property} ${unit} at ${receivedAt}. We're dispatching a 24/7 technician now under your ${usd(limit)} pre-approval and will update you once the source is found.`;
  },
  ownerApproval({ first, property, unit, cause, work, estimate, limit }) {
    return `Hi ${first}, update on ${property} ${unit}: the leak is stopped${cause ? ` (${cause})` : ""}. Follow-up repair needed: ${work}, estimated ${usd(estimate)} — above your ${usd(limit)} pre-approval. Reply YES to approve or NO and we'll call you.`;
  },
  ownerUpdate({ first, property, unit, text }) {
    return `Hi ${first}, update on ${property} ${unit}: ${text}`;
  },
};

export const CATEGORY_LABEL = {
  water_leak: "Water leak",
  plumbing: "Plumbing",
  electrical: "Electrical hazard",
  hvac: "Heating / cooling",
  appliance: "Appliance",
  gas: "Gas smell / CO",
  fire: "Fire / smoke",
  sewage: "Sewage backup",
  security: "Security",
  injury: "Injury",
  structural: "Ceiling / structural",
  lockout: "Lockout",
  pest: "Pests",
  mold: "Mold",
  life_safety_device: "Smoke/CO detector",
  general: "General request",
  non_maintenance: "Non-maintenance question",
};

/** Trades to dispatch per category when a model (not a rule) set the category. */
export const TRADES_FOR = {
  water_leak: ["plumbing"],
  plumbing: ["plumbing"],
  sewage: ["plumbing"],
  electrical: ["electrical"],
  hvac: ["hvac"],
  appliance: ["appliance"],
  lockout: ["locksmith"],
  security: ["locksmith"],
  structural: ["plumbing"],
  mold: ["mold"],
  pest: ["pest"],
  general: ["handyman"],
};
